TABLES = [{'table': 'hog', 'ES': 'Hogares', 'EN': 'Households'},
          {'table': 'nuc', 'ES': 'Parejas y otros núcleos familiares', 'EN': 'Couples and other family nuclei'},
          {'table': 'per.estu', 'ES': 'Personas empadronadas en establecimientos colectivos',
           'EN': 'Persons registered in collective housing'},
          {'table': 'per.ocu', 'ES': 'Personas residentes en viviendas familiares',
           'EN': 'Persons resident in family dwellings'},
          {'table': 'per.ppal', 'ES': 'Total de Personas', 'EN': 'All persons'},
          {'table': 'viv.fam', 'ES': 'Viviendas familiares', 'EN': 'Dwellings'},
          {'table': 'viv.ppal', 'ES': 'Ocupados de 16 y más años', 'EN': 'Employed persons aged 16 years and over'}]

LANGUAGES = [{'language': 'EN', 'description': 'inglés'}, {'language': 'ES', 'description': 'castellano'}]

METRICS = [{'table': 'hog', 'metric': 'SHOGARES', 'ES': 'Número de Hogares', 'EN': 'No. of Households'},
           {'table': 'hog', 'metric': 'MEDIA_SSUPERFICIE_OCU', 'ES': 'Superficie media por ocupante',
            'EN': 'Average floor space by occupant'},
           {'table': 'hog', 'metric': 'STAM_HOG', 'ES': 'Tamaño medio del hogar', 'EN': 'Average size of household'},
           {'table': 'nuc', 'metric': 'SNUCLEOS', 'ES': 'Número de núcleos', 'EN': 'No. of nucleus'},
           {'table': 'nuc', 'metric': 'MEDIA_SHIJOS_NUCLEO', 'ES': 'Número medio de hijos por núcleo familiar',
            'EN': 'Average no. of children per family nucleus'},
           {'table': 'per.estu', 'metric': 'SPERSONAS', 'ES': 'Personas', 'EN': 'People'},
           {'table': 'per.estu', 'metric': 'MEDIA_SEDAD', 'ES': 'Edad media', 'EN': 'Average age'},
           {'table': 'per.estu', 'metric': 'PCT_SMENORES_16', 'ES': 'Porcentaje de personas de menos de 16 años',
            'EN': 'Percentage of people under 16 years'},
           {'table': 'per.estu', 'metric': 'PCT_SPERSONAS_16_64', 'ES': 'Porcentaje de personas entre 16 y 64 años',
            'EN': 'Percentage of people between the ages of 16 and 64'},
           {'table': 'per.estu', 'metric': 'PCT_SMAYORES_64', 'ES': 'Porcentaje de personas de más de 64 años',
            'EN': 'Percentage of people over 64 years'},
           {'table': 'per.estu', 'metric': 'PCT_SEXTRANJEROS', 'ES': 'Porcentaje de población extranjera',
            'EN': 'Percentage of foreign people'},
           {'table': 'per.estu', 'metric': 'MEDIA_SNIVEL_ESTU', 'ES': 'Nivel medio de estudios',
            'EN': 'Average level of studies'},
           {'table': 'per.estu', 'metric': 'PCT_SESTSUP', 'ES': 'Porcentaje de personas con estudios superiores',
            'EN': 'Percentage of people with higher education'}, {'table': 'per.estu', 'metric': 'PCT_SNACIO',
                                                                  'ES': 'Porcentaje de personas con país de nacimiento extranjero',
                                                                  'EN': 'Percentage of people with a foreign country of birth'},
           {'table': 'per.estu', 'metric': 'PCT_SACTIVOS', 'ES': 'Porcentaje de población activa',
            'EN': 'Percentage of active people'},
           {'table': 'per.ocu', 'metric': 'SPERSONAS', 'ES': 'Personas', 'EN': 'People'},
           {'table': 'per.ocu', 'metric': 'MEDIA_SEDAD', 'ES': 'Edad media', 'EN': 'Average age'},
           {'table': 'per.ocu', 'metric': 'PCT_SMENORES_16', 'ES': 'Porcentaje de personas de menos de 16 años',
            'EN': 'Percentage of people under 16 years'},
           {'table': 'per.ocu', 'metric': 'PCT_SPERSONAS_16_64', 'ES': 'Porcentaje de personas entre 16 y 64 años',
            'EN': 'Percentage of people between the ages of 16 and 64'},
           {'table': 'per.ocu', 'metric': 'PCT_SMAYORES_64', 'ES': 'Porcentaje de personas de más de 64 años',
            'EN': 'Percentage of people over 64 years'},
           {'table': 'per.ocu', 'metric': 'PCT_SEXTRANJEROS', 'ES': 'Porcentaje de población extranjera',
            'EN': 'Percentage of foreign people'},
           {'table': 'per.ocu', 'metric': 'MEDIA_SNIVEL_ESTU', 'ES': 'Nivel medio de estudios',
            'EN': 'Average level of studies'},
           {'table': 'per.ocu', 'metric': 'PCT_SESTSUP', 'ES': 'Porcentaje de personas con estudios superiores',
            'EN': 'Percentage of people with higher education'}, {'table': 'per.ocu', 'metric': 'PCT_SNACIO',
                                                                  'ES': 'Porcentaje de personas con país de nacimiento extranjero',
                                                                  'EN': 'Percentage of people with a foreign country of birth'},
           {'table': 'per.ocu', 'metric': 'PCT_SACTIVOS', 'ES': 'Porcentaje de población activa',
            'EN': 'Percentage of active people'},
           {'table': 'per.ppal', 'metric': 'SPERSONAS', 'ES': 'Personas', 'EN': 'People'},
           {'table': 'per.ppal', 'metric': 'MEDIA_SEDAD', 'ES': 'Edad media', 'EN': 'Average age'},
           {'table': 'per.ppal', 'metric': 'PCT_SESTSUP', 'ES': 'Porcentaje de personas con estudios superiores',
            'EN': 'Percentage of people with higher education'},
           {'table': 'per.ppal', 'metric': 'PCT_SMENORES_16', 'ES': 'Porcentaje de personas de menos de 16 años',
            'EN': 'Percentage of people under 16 years'},
           {'table': 'per.ppal', 'metric': 'PCT_SPERSONAS_16_64', 'ES': 'Porcentaje de personas entre 16 y 64 años',
            'EN': 'Percentage of people between the ages of 16 and 64'},
           {'table': 'per.ppal', 'metric': 'PCT_SMAYORES_64', 'ES': 'Porcentaje de personas de más de 64 años',
            'EN': 'Percentage of people over 64 years'},
           {'table': 'per.ppal', 'metric': 'PCT_SEXTRANJEROS', 'ES': 'Porcentaje de población extranjera',
            'EN': 'Percentage of foreign people'},
           {'table': 'per.ppal', 'metric': 'MEDIA_SNIVEL_ESTU', 'ES': 'Nivel medio de estudios',
            'EN': 'Average level of studies'}, {'table': 'per.ppal', 'metric': 'PCT_SNACIO',
                                                'ES': 'Porcentaje de personas con país de nacimiento extranjero',
                                                'EN': 'Percentage of people with a foreign country of birth'},
           {'table': 'per.ppal', 'metric': 'PCT_SACTIVOS', 'ES': 'Porcentaje de población activa',
            'EN': 'Percentage of active people'},
           {'table': 'per.ppal', 'metric': 'PCT_SINACTIVOS', 'ES': 'Porcentaje de población inactiva',
            'EN': 'Percentage of inactive people'},
           {'table': 'per.ppal', 'metric': 'PCT_SPARADOS', 'ES': 'Porcentaje de población parada',
            'EN': 'Percentage of unemployed people'},
           {'table': 'per.ppal', 'metric': 'PCT_SOCUPADOS', 'ES': 'Porcentaje de población ocupada',
            'EN': 'Percentage of employed people'},
           {'table': 'viv.fam', 'metric': 'SVIVIENDAS', 'ES': 'Número de viviendas', 'EN': 'No. of dwellings'},
           {'table': 'viv.fam', 'metric': 'MEDIA_SANTIGUEDAD', 'ES': 'Edad media de la vivienda',
            'EN': 'Average age of the dwelling'},
           {'table': 'viv.fam', 'metric': 'MEDIA_SSUPERFICIE', 'ES': 'Superficie media',
            'EN': 'Average useful floor space'},
           {'table': 'viv.fam', 'metric': 'PCT_SVIVNOPPAL', 'ES': 'Porcentaje de viviendas no principales',
            'EN': 'Percentage of seasonal/empty dwellings'},
           {'table': 'viv.ppal', 'metric': 'SPERSONAS', 'ES': 'Personas', 'EN': 'People'},
           {'table': 'viv.ppal', 'metric': 'MEDIA_SEDAD', 'ES': 'Edad media', 'EN': 'Average age'},
           {'table': 'viv.ppal', 'metric': 'PCT_SPERSONAS_16_64', 'ES': 'Porcentaje de personas entre 16 y 64 años',
            'EN': 'Percentage of people between the ages of 16 and 64'},
           {'table': 'viv.ppal', 'metric': 'PCT_SMAYORES_64', 'ES': 'Porcentaje de personas de más de 64 años',
            'EN': 'Percentage of people over 64 years'},
           {'table': 'viv.ppal', 'metric': 'PCT_SEXTRANJEROS', 'ES': 'Porcentaje de población extranjera',
            'EN': 'Percentage of foreign people'},
           {'table': 'viv.ppal', 'metric': 'MEDIA_SNIVEL_ESTU', 'ES': 'Nivel medio de estudios',
            'EN': 'Average level of studies'},
           {'table': 'viv.ppal', 'metric': 'PCT_SESTSUP', 'ES': 'Porcentaje de personas con estudios superiores',
            'EN': 'Percentage of people with higher education'}, {'table': 'viv.ppal', 'metric': 'PCT_SNACIO',
                                                                  'ES': 'Porcentaje de personas con país de nacimiento extranjero',
                                                                  'EN': 'Percentage of people with a foreign country of birth'},
           {'table': 'viv.ppal', 'metric': 'PCT_SACTIVOS', 'ES': 'Porcentaje de población activa',
            'EN': 'Percentage of active people'}]

VARIABLES = [
    {'table': 'hog', 'variable': 'ID_ACTI_HOG_1', 'ES': 'Número de miembros de 16 a 64 años que están trabajando',
     'EN': 'Number of employed  members  from 16 to 64 years old'},
    {'table': 'hog', 'variable': 'ID_ACTI_HOG_2', 'ES': 'Número de miembros de 16 a 64 años que están parados',
     'EN': 'Number of unemployed  members  from 16 to 64 years old'}, {'table': 'hog', 'variable': 'ID_ACTI_HOG_3',
                                                                       'ES': 'Número de miembros de 16 a 64 años que están en situación de inactividad',
                                                                       'EN': 'Number of economically inactive members from 16 to 64 years old '},
    {'table': 'hog', 'variable': 'ID_ANO_CONS_GR11', 'ES': 'Año de construcción (agregado)',
     'EN': 'Year of construction  (aggregated)'},
    {'table': 'hog', 'variable': 'ID_CLASE_VIV_FAM', 'ES': 'Clase de vivienda familiar',
     'EN': 'Class of main family dwelling'},
    {'table': 'hog', 'variable': 'ID_ESTRUC_HOG_2', 'ES': 'Estructura del hogar', 'EN': 'Household Structure '},
    {'table': 'hog', 'variable': 'ID_FAM_HOG', 'ES': 'Número familias en el hogar',
     'EN': 'Number of families in the household'},
    {'table': 'hog', 'variable': 'ID_NUC_HOG', 'ES': 'Número núcleos en el hogar',
     'EN': 'Number of family nuclei in the household'},
    {'table': 'hog', 'variable': 'ID_RESIDENCIA_N1', 'ES': 'CC.AA. de residencia', 'EN': 'Autonomous Community'},
    {'table': 'hog', 'variable': 'ID_RESIDENCIA_N2', 'ES': 'Provincia de residencia', 'EN': 'Province of residence'},
    {'table': 'hog', 'variable': 'ID_RESIDENCIA_N3', 'ES': 'Municipio de residencia',
     'EN': 'Municipality of residence'},
    {'table': 'hog', 'variable': 'ID_RESIDENCIA_N4', 'ES': 'Distrito ', 'EN': 'District '},
    {'table': 'hog', 'variable': 'ID_RESIDENCIA_N5', 'ES': 'Sección ', 'EN': 'Section'},
    {'table': 'hog', 'variable': 'ID_SUP_OCU_VIV', 'ES': 'Superficie por ocupante',
     'EN': 'Useful floor space per occupant'},
    {'table': 'hog', 'variable': 'ID_SUP_VIV', 'ES': 'Superficie ', 'EN': 'Useful floor space'},
    {'table': 'hog', 'variable': 'ID_TAM_HOG_6', 'ES': 'Tamaño del hogar', 'EN': 'Size of the household '},
    {'table': 'hog', 'variable': 'ID_TAM_MUN_HOG', 'ES': 'Tamaño de municipio de residencia',
     'EN': 'Size of municipality of residence'},
    {'table': 'hog', 'variable': 'ID_TAMEDAD04', 'ES': 'Número de miembros de 0 a 4 años',
     'EN': 'Number of members from 0 to 4 years'},
    {'table': 'hog', 'variable': 'ID_TAMEDAD1624', 'ES': 'Número de miembros de 16 a 24 años',
     'EN': 'Number of members from 16 to 24 years old'},
    {'table': 'hog', 'variable': 'ID_TAMEDAD2534', 'ES': 'Número de miembros de 25 a 34 años',
     'EN': 'Number of members from 25 to 34 years old'},
    {'table': 'hog', 'variable': 'ID_TAMEDAD3564', 'ES': 'Número de miembros de 35 a 64 años',
     'EN': 'Number of members from 35 to 64 years old'},
    {'table': 'hog', 'variable': 'ID_TAMEDAD515', 'ES': ' Número de miembros de 5 a 15 años',
     'EN': 'Number of members from 5 to 15 years old'},
    {'table': 'hog', 'variable': 'ID_TAMEDAD6584', 'ES': 'Número de miembros de 65 a 84 años',
     'EN': 'Number of members from 65 to 84 years old'},
    {'table': 'hog', 'variable': 'ID_TAMEDAD85m', 'ES': 'Número de miembros de 85 años o más',
     'EN': 'Number of members 85 years and above'},
    {'table': 'hog', 'variable': 'ID_TAMSEXNAC11', 'ES': 'Hombres españoles que viven en el hogar',
     'EN': 'Spanish men living in the household'},
    {'table': 'hog', 'variable': 'ID_TAMSEXNAC12', 'ES': 'Hombres extranjeros que viven en el hogar',
     'EN': 'Foreign men living in the household'},
    {'table': 'hog', 'variable': 'ID_TAMSEXNAC13', 'ES': 'Mujeres españolas que viven en el hogar',
     'EN': 'Spanish women living in the household'},
    {'table': 'hog', 'variable': 'ID_TAMSEXNAC14', 'ES': 'Mujeres extranjeras que viven en el hogar',
     'EN': 'Foreign women living in the household'},
    {'table': 'hog', 'variable': 'ID_TENEN_VIV', 'ES': 'Régimen de tenencia de la vivienda',
     'EN': 'Tenure status of dwelling '},
    {'table': 'hog', 'variable': 'ID_TIPO_EDIF_VIV', 'ES': 'Tipo de viviendas según tipo de edificio ',
     'EN': 'Type of dwellings according to type of building '},
    {'table': 'hog', 'variable': 'ID_TIPO_HOG_1', 'ES': 'Tipo de Hogar (detalle)', 'EN': 'Type of Household (detail)'},
    {'table': 'hog', 'variable': 'ID_TIPO_MUN_DEGURBA', 'ES': 'Tipo de municipio según grado de urbanización',
     'EN': 'Type of municipality according to degree of urbanization'},
    {'table': 'nuc', 'variable': 'ID_ANO_CONS_GR11', 'ES': 'Año de construcción (agregado)',
     'EN': 'Year of construction  (aggregated)'},
    {'table': 'nuc', 'variable': 'ID_CLASE_VIV_FAM', 'ES': 'Clase de vivienda familiar',
     'EN': 'Class of main family dwelling'},
    {'table': 'nuc', 'variable': 'ID_DIF_EDAD_NUC', 'ES': 'Diferencia de edad entre los miembros del núcleo',
     'EN': 'Age difference between family nucleus members'},
    {'table': 'nuc', 'variable': 'ID_ESTRUC_HOG_2', 'ES': 'Estructura del hogar', 'EN': 'Household Structure '},
    {'table': 'nuc', 'variable': 'ID_FAM_HOG', 'ES': 'Número familias en el hogar',
     'EN': 'Number of families in the household'},
    {'table': 'nuc', 'variable': 'ID_NHIJOS_COM_NUC', 'ES': 'Número de hijos comunes',
     'EN': 'Number of common children'},
    {'table': 'nuc', 'variable': 'ID_NHIJOS_NUC', 'ES': 'Número de hijos', 'EN': 'Number of children'},
    {'table': 'nuc', 'variable': 'ID_NUC_HOG', 'ES': 'Número núcleos en el hogar',
     'EN': 'Number of family nuclei in the household'},
    {'table': 'nuc', 'variable': 'ID_RESIDENCIA_N1', 'ES': 'CC.AA. de residencia', 'EN': 'Autonomous Community'},
    {'table': 'nuc', 'variable': 'ID_RESIDENCIA_N2', 'ES': 'Provincia de residencia', 'EN': 'Province of residence'},
    {'table': 'nuc', 'variable': 'ID_RESIDENCIA_N3', 'ES': 'Municipio de residencia',
     'EN': 'Municipality of residence'},
    {'table': 'nuc', 'variable': 'ID_RESIDENCIA_N4', 'ES': 'Distrito ', 'EN': 'District '},
    {'table': 'nuc', 'variable': 'ID_RESIDENCIA_N5', 'ES': 'Sección ', 'EN': 'Section'},
    {'table': 'nuc', 'variable': 'ID_SUP_OCU_VIV', 'ES': 'Superficie por ocupante',
     'EN': 'Useful floor space per occupant'},
    {'table': 'nuc', 'variable': 'ID_SUP_VIV', 'ES': 'Superficie ', 'EN': 'Useful floor space'},
    {'table': 'nuc', 'variable': 'ID_TAM_HOG_6', 'ES': 'Tamaño del hogar', 'EN': 'Size of the household '},
    {'table': 'nuc', 'variable': 'ID_TAM_MUN_NUC', 'ES': 'Tamaño de municipio de residencia',
     'EN': 'Size of municipality of residence'},
    {'table': 'nuc', 'variable': 'ID_TAM_NUC_1', 'ES': 'Tamaño del núcleo', 'EN': 'Family nucleus size'},
    {'table': 'nuc', 'variable': 'ID_TENEN_VIV', 'ES': 'Régimen de tenencia de la vivienda',
     'EN': 'Tenure status of dwelling '},
    {'table': 'nuc', 'variable': 'ID_TIPO_EDIF_VIV', 'ES': 'Tipo de viviendas según tipo de edificio ',
     'EN': 'Type of dwellings according to type of building '},
    {'table': 'nuc', 'variable': 'ID_TIPO_HOG_1', 'ES': 'Tipo de Hogar (detalle)', 'EN': 'Type of Household (detail)'},
    {'table': 'nuc', 'variable': 'ID_TIPO_MUN_DEGURBA_NUC', 'ES': 'Tipo de municipio según grado de urbanización',
     'EN': 'Type of municipality according to degree of urbanization'},
    {'table': 'nuc', 'variable': 'ID_TIPO_NUC_1', 'ES': 'Tipo de núcleo', 'EN': 'Type of Family Nucleus'},
    {'table': 'nuc', 'variable': 'ID_TIPO_PAR_NUC_1', 'ES': 'Tipo de pareja (de hecho o de derecho)',
     'EN': 'Type of couple (de facto or de jure)'},
    {'table': 'nuc', 'variable': 'ID_TIPO_PAR_NUC_2', 'ES': 'Tipo de pareja (mismo sexo', 'EN': 'distinto sexo)',
     None: ['Type of couple (same sex', 'different sex)']},
    {'table': 'per.estu', 'variable': 'ID_EDAD', 'ES': 'Edad año a año', 'EN': 'Age year to year'},
    {'table': 'per.estu', 'variable': 'ID_ESCUR', 'ES': 'Nivel más alto de la enseñanza principal que cursa',
     'EN': 'Highest level of the primary studies in course'},
    {'table': 'per.estu', 'variable': 'ID_ESCUR2', 'ES': 'Nivel más alto de otras enseñanzas',
     'EN': 'si cursa más de una', None: ['Highest level of other studies', 'if more than one is being pursued']},
    {'table': 'per.estu', 'variable': 'ID_ESREAL_CNEDA', 'ES': 'Nivel de estudios (detalle)',
     'EN': 'Educational attainment (detail)'},
    {'table': 'per.estu', 'variable': 'ID_ESREAL_GR5', 'ES': 'Nivel de estudios (grado)',
     'EN': 'Educational attainment (grade)'},
    {'table': 'per.estu', 'variable': 'ID_ESTADO_CIVIL', 'ES': 'Estado Civil', 'EN': 'Legal Marital Status'},
    {'table': 'per.estu', 'variable': 'ID_GRAN_GRUPO_EDAD', 'ES': 'Edad en grandes grupos',
     'EN': 'Age in large groups'},
    {'table': 'per.estu', 'variable': 'ID_GRUPO_Q_EDAD', 'ES': 'Edad (grupos quinquenales)',
     'EN': 'Age (five-year groups)'},
    {'table': 'per.estu', 'variable': 'ID_LUGAR_NAC_EXT_N1', 'ES': 'Lugar de nacimiento (España/Extranjero)',
     'EN': 'Place of birth (Spain/abroad)'},
    {'table': 'per.estu', 'variable': 'ID_LUGAR_NAC_EXT_N2', 'ES': 'País de nacimiento (grandes grupos)',
     'EN': 'Country of birth (large groups)'},
    {'table': 'per.estu', 'variable': 'ID_LUGAR_NAC_NAC_N1', 'ES': 'CC.AA. de nacimiento',
     'EN': 'Autonomous Community of birth'},
    {'table': 'per.estu', 'variable': 'ID_LUGAR_NAC_NAC_N2', 'ES': 'Provincia de nacimiento',
     'EN': 'Province of birth'},
    {'table': 'per.estu', 'variable': 'ID_LUGAR_NAC_NAC_N3', 'ES': 'Municipio de nacimiento',
     'EN': 'Municipality of birth'},
    {'table': 'per.estu', 'variable': 'ID_NACIONALIDAD_N1', 'ES': 'Nacionalidad (española/extranjera)',
     'EN': 'Nationality (Spanish/foreign)'},
    {'table': 'per.estu', 'variable': 'ID_NACIONALIDAD_N2', 'ES': 'Nacionalidad (grandes grupos)',
     'EN': 'Nationality (large groups)'},
    {'table': 'per.estu', 'variable': 'ID_PAIS_ANT_GR9', 'ES': 'País de residencia anterior (agregado) ',
     'EN': 'Country of previous residence (aggregated) '},
    {'table': 'per.estu', 'variable': 'ID_PAIS_DANO_GR10', 'ES': 'País residencia en 2011 (agregado)',
     'EN': 'Country of residence in 2011 (aggregated) '},
    {'table': 'per.estu', 'variable': 'ID_PAIS_PR_GR9', 'ES': 'País de procedencia (grandes grupos)',
     'EN': 'Country of origin (large groups)'},
    {'table': 'per.estu', 'variable': 'ID_PAIS_UNANO_GR10', 'ES': 'País de residencia en 2020 (agregado)',
     'EN': 'Country of residence in 2020  (aggregated) '},
    {'table': 'per.estu', 'variable': 'ID_RELA', 'ES': 'Relación preferente con la actividad (detalle)',
     'EN': 'Current activity status (detail)'},
    {'table': 'per.estu', 'variable': 'ID_RELA2', 'ES': 'Relación preferente con la actividad (activo /inactivo)',
     'EN': 'Current activity status (active/inactive)'},
    {'table': 'per.estu', 'variable': 'ID_RESI_2011_N1', 'ES': 'CC.AA. de residencia en 2011',
     'EN': 'Autonomous Community of residence in 2011'},
    {'table': 'per.estu', 'variable': 'ID_RESI_2011_N2', 'ES': 'Provincia de residencia en 2011',
     'EN': 'Province of residence in 2011'},
    {'table': 'per.estu', 'variable': 'ID_RESI_2011_N3', 'ES': 'Municipio de residencia en 2011',
     'EN': 'Municipality of residence in 2011'},
    {'table': 'per.estu', 'variable': 'ID_RESI_2020_N1', 'ES': 'CC.AA. de residencia en 2020',
     'EN': 'Autonomous Community of residence in 2020'},
    {'table': 'per.estu', 'variable': 'ID_RESI_2020_N2', 'ES': 'Provincia de residencia en 2020',
     'EN': 'Province of residence in 2020'},
    {'table': 'per.estu', 'variable': 'ID_RESI_2020_N3', 'ES': 'Municipio de residencia en 2020',
     'EN': 'Municipality of residence 2020'},
    {'table': 'per.estu', 'variable': 'ID_RESI_ANT', 'ES': 'Relación entre residencia anterior y residencia actual ',
     'EN': 'Relationship between previous residence and current residence '},
    {'table': 'per.estu', 'variable': 'ID_RESI_DANO', 'ES': 'Relación entre residencia en 2011 y actual ',
     'EN': 'Relationship between residence in 2011 and current residence '},
    {'table': 'per.estu', 'variable': 'ID_RESI_NACIM', 'ES': 'Relación entre lugar de nacimiento y residencia',
     'EN': 'Relationship between place of birth and residence'},
    {'table': 'per.estu', 'variable': 'ID_RESI_UNANO', 'ES': 'Relación entre residencia en 2020 y actual',
     'EN': 'Relationship between residence in 2020 and current residence '},
    {'table': 'per.estu', 'variable': 'ID_RESIDENCIA_N1', 'ES': 'CC.AA. de residencia', 'EN': 'Autonomous Community'},
    {'table': 'per.estu', 'variable': 'ID_RESIDENCIA_N2', 'ES': 'Provincia de residencia',
     'EN': 'Province of residence'},
    {'table': 'per.estu', 'variable': 'ID_RESIDENCIA_N3', 'ES': 'Municipio de residencia',
     'EN': 'Municipality of residence'},
    {'table': 'per.estu', 'variable': 'ID_RESIDENCIA_N4', 'ES': 'Distrito ', 'EN': 'District '},
    {'table': 'per.estu', 'variable': 'ID_RESIDENCIA_N5', 'ES': 'Sección ', 'EN': 'Section'},
    {'table': 'per.estu', 'variable': 'ID_SEXO', 'ES': 'Sexo', 'EN': 'Sex'},
    {'table': 'per.estu', 'variable': 'ID_TAM_MUN_11', 'ES': 'Tamaño de municipio de residencia',
     'EN': 'Size of municipality of residence'},
    {'table': 'per.estu', 'variable': 'ID_TAM_MUN_12', 'ES': 'Tamaño de municipio de nacimiento',
     'EN': 'Size of municipality of birth'},
    {'table': 'per.estu', 'variable': 'ID_TAM_MUN_ANT_12', 'ES': 'Tamaño de municipio de residencia anterior',
     'EN': 'Size of municipality previous residence'},
    {'table': 'per.estu', 'variable': 'ID_TAMANO_MUN_DANO', 'ES': 'Tamaño de municipio de residencia en 2011',
     'EN': 'Size of municipality of residence in 2011'},
    {'table': 'per.estu', 'variable': 'ID_TAMANO_MUN_UNANO', 'ES': 'Tamaño de municipio de residencia en 2020',
     'EN': 'Size of municipality of residence in 2020'},
    {'table': 'per.estu', 'variable': 'ID_TIPO_COL', 'ES': 'Tipo de colectivo (detalle)',
     'EN': 'Class of collective living quarter (detail)'},
    {'table': 'per.estu', 'variable': 'ID_TIPO_COL_AG', 'ES': 'Tipo de colectivo (agregado)',
     'EN': 'Class of collective living quarter (aggregated)'},
    {'table': 'per.estu', 'variable': 'ID_TIPO_MUN_DEGURBA', 'ES': 'Tipo de municipio según grado de urbanización',
     'EN': 'Type of municipality according to degree of urbanization'},
    {'table': 'per.estu', 'variable': 'ID_ULT_RESI_ANT_N1', 'ES': 'CC.AA. de residencia anterior',
     'EN': 'Previous Autonomous Community of residence'},
    {'table': 'per.estu', 'variable': 'ID_ULT_RESI_ANT_N2', 'ES': 'Provincia de residencia anterior',
     'EN': 'Previous Province of residence'},
    {'table': 'per.estu', 'variable': 'ID_ULT_RESI_ANT_N3', 'ES': 'Municipio de residencia anterior',
     'EN': 'Previous Municipality of residence'},
    {'table': 'per.estu', 'variable': 'ID_VARANOE', 'ES': 'Año de llegada a España', 'EN': 'Year of arrival to Spain'},
    {'table': 'per.ocu', 'variable': 'ID_ACT5', 'ES': 'Actividad establecimiento (rama)',
     'EN': 'Economic activity  (branch)'},
    {'table': 'per.ocu', 'variable': 'ID_ANO_CONS_GR11', 'ES': 'Año de construcción (agregado)',
     'EN': 'Year of construction  (aggregated)'},
    {'table': 'per.ocu', 'variable': 'ID_CLASE_VIV', 'ES': 'Clase de vivienda', 'EN': 'Class of Dwelling'},
    {'table': 'per.ocu', 'variable': 'ID_EDAD', 'ES': 'Edad año a año', 'EN': 'Age year to year'},
    {'table': 'per.ocu', 'variable': 'ID_EDAD_CON_GR22', 'ES': 'Edad del cónyuge (grupos quinquenales)',
     'EN': 'Age of spouse or partner (five-year groups)'},
    {'table': 'per.ocu', 'variable': 'ID_EDAD_MAD_GR22', 'ES': 'Edad del progenitor 1 (grupos quinquenales)',
     'EN': 'Age of parent 1 (five-year groups)'},
    {'table': 'per.ocu', 'variable': 'ID_EDAD_PAD_GR22', 'ES': 'Edad del progenitor 2 (grupos quinquenales)',
     'EN': 'Age of parent 2 (five-year groups)'},
    {'table': 'per.ocu', 'variable': 'ID_ESCUR', 'ES': 'Nivel más alto de la enseñanza principal que cursa',
     'EN': 'Highest level of the primary studies in course'},
    {'table': 'per.ocu', 'variable': 'ID_ESCUR2', 'ES': 'Nivel más alto de otras enseñanzas',
     'EN': 'si cursa más de una', None: ['Highest level of other studies', 'if more than one is being pursued']},
    {'table': 'per.ocu', 'variable': 'ID_ESREAL_CNEDA', 'ES': 'Nivel de estudios (detalle)',
     'EN': 'Educational attainment (detail)'},
    {'table': 'per.ocu', 'variable': 'ID_ESREAL_CNEDA_CON', 'ES': 'Nivel de estudios del cónyuge (detalle)',
     'EN': 'Educational attainment of spouse or partner (detail)'},
    {'table': 'per.ocu', 'variable': 'ID_ESREAL_CNEDA_MAD', 'ES': 'Nivel de estudios del progenitor 1 (detalle)',
     'EN': 'Educational attainment of parent 1 (detail)'},
    {'table': 'per.ocu', 'variable': 'ID_ESREAL_CNEDA_PAD', 'ES': 'Nivel de estudios del progenitor 2 (detalle)',
     'EN': 'Educational attainment of parent 2 (detail)'},
    {'table': 'per.ocu', 'variable': 'ID_ESREAL_GR5', 'ES': 'Nivel de estudios (grado)',
     'EN': 'Educational attainment (grade)'},
    {'table': 'per.ocu', 'variable': 'ID_ESREAL_GR5_CON', 'ES': 'Nivel de estudios del cónyuge (grado)',
     'EN': 'Educational attainment of spouse or partner (grade)'},
    {'table': 'per.ocu', 'variable': 'ID_ESREAL_GR5_MAD', 'ES': 'Nivel de estudios del progenitor 1 (grado)',
     'EN': 'Educational attainment of parent 1 (grade)'},
    {'table': 'per.ocu', 'variable': 'ID_ESREAL_GR5_PAD', 'ES': 'Nivel de estudios del progenitor 2 (grado)',
     'EN': 'Educational attainment of parent 2 (grade)'},
    {'table': 'per.ocu', 'variable': 'ID_ESTADO_CIVIL', 'ES': 'Estado Civil', 'EN': 'Legal Marital Status'},
    {'table': 'per.ocu', 'variable': 'ID_ESTADO_CIVIL_CON', 'ES': 'Estado civil del cónyuge',
     'EN': 'Legal Marital status spouse or partner'},
    {'table': 'per.ocu', 'variable': 'ID_ESTADO_CIVIL_MAD', 'ES': 'Estado civil del progenitor 1',
     'EN': 'Legal Marital status of parent 1'},
    {'table': 'per.ocu', 'variable': 'ID_ESTADO_CIVIL_PAD', 'ES': 'Estado civil del  progenitor 2',
     'EN': 'Legal Marital status of parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_ESTRUC_HOG_2', 'ES': 'Estructura del hogar', 'EN': 'Household Structure '},
    {'table': 'per.ocu', 'variable': 'ID_FAM_HOG', 'ES': 'Número familias en el hogar',
     'EN': 'Number of families in the household'},
    {'table': 'per.ocu', 'variable': 'ID_GRAN_GRUPO_EDAD', 'ES': 'Edad en grandes grupos', 'EN': 'Age in large groups'},
    {'table': 'per.ocu', 'variable': 'ID_GRUPO_Q_EDAD', 'ES': 'Edad (grupos quinquenales)',
     'EN': 'Age (five-year groups)'}, {'table': 'per.ocu', 'variable': 'ID_I_CON', 'ES': 'Vive con cónyuge o pareja',
                                       'EN': 'Cohabiting with the spouse or partner'},
    {'table': 'per.ocu', 'variable': 'ID_I_MAD', 'ES': 'Vive con progenitor 1', 'EN': 'Cohabiting with parent 1'},
    {'table': 'per.ocu', 'variable': 'ID_I_OPA', 'ES': 'Vive con otro pariente',
     'EN': 'Cohabiting with other relative'},
    {'table': 'per.ocu', 'variable': 'ID_I_PAD', 'ES': 'Vive con progenitor 2', 'EN': 'Cohabiting with parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_L_EST8', 'ES': 'Lugar de estudio', 'EN': 'Place of study'},
    {'table': 'per.ocu', 'variable': 'ID_L_TRAB7', 'ES': 'Lugar de trabajo', 'EN': 'Place of work'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_EST_N1', 'ES': 'CC.AA. de estudio',
     'EN': 'Autonomous Community of study'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_EST_N2', 'ES': 'Provincia de estudio', 'EN': 'Province of study'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_EST_N3', 'ES': 'Municipio de estudio', 'EN': 'Municipality of study'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_CON_N1', 'ES': 'CC.AA. de nacimiento del cónyuge ',
     'EN': 'Autonomous Community of birth of spouse or partner '},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_CON_N2', 'ES': 'Provincia de nacimiento del cónyuge',
     'EN': 'Province of birth of spouse or partner'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_CON_N3', 'ES': 'Municipio de nacimiento del cónyuge',
     'EN': 'Municipality of birth of spouse or partner'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_EXT_CON_N1', 'ES': 'Lugar de nacimiento del cónyuge (agregado)',
     'EN': 'Place of birth of spouse or partner (aggregated)'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_EXT_CON_N2', 'ES': 'País de nacimiento del cónyuge (grandes grupos)',
     'EN': 'Country of birth of spouse or partner  (large groups)'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_EXT_CON_N3', 'ES': 'País de nacimiento del cónyuge',
     'EN': 'Country of birth of spouse or partner'}, {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_EXT_MAD_N1',
                                                      'ES': 'Lugar de nacimiento del progenitor 1 (española/extranjera) ',
                                                      'EN': 'Place of birth of parent 1 (aggregated)'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_EXT_MAD_N2',
     'ES': 'País de nacimiento del progenitor 1 (grandes grupos)', 'EN': 'Country of birth (large groups)'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_EXT_MAD_N3', 'ES': 'País de nacimiento del progenitor 1',
     'EN': 'Country of  birth parent 1'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_EXT_N1', 'ES': 'Lugar de nacimiento (España/Extranjero)',
     'EN': 'Place of birth (Spain/abroad)'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_EXT_N2', 'ES': 'País de nacimiento (grandes grupos)',
     'EN': 'Country of birth (large groups)'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_EXT_N3', 'ES': 'País de nacimiento', 'EN': 'Country of birth'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_EXT_PAD_N1', 'ES': 'Lugar de nacimiento del progenitor 2 (agregado)',
     'EN': 'Place of birth (aggregate) of parent 2'}, {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_EXT_PAD_N2',
                                                       'ES': 'País de nacimiento del progenitor 2 (grandes grupos)',
                                                       'EN': 'Country of birth (large groups) of parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_EXT_PAD_N3', 'ES': 'País de nacimiento del progenitor 2',
     'EN': 'Country of birth parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_MAD_N1', 'ES': 'CC.AA. de nacimiento del progenitor 1 ',
     'EN': 'Birth Autonomous Community of parent 1 '},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_MAD_N2', 'ES': 'Provincia de nacimiento del progenitor 1',
     'EN': 'Birth province of parent 1'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_MAD_N3', 'ES': 'Municipio de nacimiento del progenitor 1',
     'EN': 'Birth municipality of parent 1'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_NAC_N1', 'ES': 'CC.AA. de nacimiento',
     'EN': 'Autonomous Community of birth'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_NAC_N2', 'ES': 'Provincia de nacimiento', 'EN': 'Province of birth'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_NAC_N3', 'ES': 'Municipio de nacimiento',
     'EN': 'Municipality of birth'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_PAD_N1', 'ES': 'CC.AA. de nacimiento del progenitor 2',
     'EN': 'Birth Autonomous Community of parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_PAD_N2', 'ES': 'Provincia de nacimiento del  progenitor 2',
     'EN': 'Birth province of parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_NAC_PAD_N3', 'ES': 'Municipio de nacimiento del  progenitor 2',
     'EN': 'Birth municipality of parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_PR_N1', 'ES': 'CC.AA. de procedencia',
     'EN': 'Autonomous Community of origin'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_PR_N2', 'ES': 'Provincia de procedencia', 'EN': 'Province of origin'},
    {'table': 'per.ocu', 'variable': 'ID_LUGAR_PR_N3', 'ES': 'Municipio de procedencia',
     'EN': 'Municipality of origin'},
    {'table': 'per.ocu', 'variable': 'ID_NACIONALIDAD_CON_N1', 'ES': 'Nacionalidad del cónyuge (española/extranjera)',
     'EN': 'Nationality of spouse or partner (Spanish/foreign)'},
    {'table': 'per.ocu', 'variable': 'ID_NACIONALIDAD_CON_N2', 'ES': 'Nacionalidad del cónyuge (grandes grupos)',
     'EN': 'Nationality of spouse or partner (large groups)'},
    {'table': 'per.ocu', 'variable': 'ID_NACIONALIDAD_CON_N3', 'ES': 'País de nacionalidad del cónyuge',
     'EN': 'Country of nationality spouse or partner'}, {'table': 'per.ocu', 'variable': 'ID_NACIONALIDAD_MAD_N1',
                                                         'ES': 'Nacionalidad del progenitor 1 (española/extranjera)',
                                                         'EN': 'Nationality of parent 1 (Spanish/foreign)'},
    {'table': 'per.ocu', 'variable': 'ID_NACIONALIDAD_MAD_N2', 'ES': 'Nacionalidad del progenitor 1 (grandes grupos)',
     'EN': 'Nationality of parent 1 (large groups)'},
    {'table': 'per.ocu', 'variable': 'ID_NACIONALIDAD_MAD_N3', 'ES': 'País de nacionalidad del progenitor 1',
     'EN': 'Country of nacionality of parent 1'},
    {'table': 'per.ocu', 'variable': 'ID_NACIONALIDAD_N1', 'ES': 'Nacionalidad (española/extranjera)',
     'EN': 'Nationality (Spanish/foreign)'},
    {'table': 'per.ocu', 'variable': 'ID_NACIONALIDAD_N2', 'ES': 'Nacionalidad (grandes grupos)',
     'EN': 'Nationality (large groups)'},
    {'table': 'per.ocu', 'variable': 'ID_NACIONALIDAD_N3', 'ES': 'País de nacionalidad',
     'EN': 'Country of nationality'}, {'table': 'per.ocu', 'variable': 'ID_NACIONALIDAD_PAD_N1',
                                       'ES': 'Nacionalidad del progenitor 2 (española/extranjera)',
                                       'EN': 'Nationality of parent 2 (Spanish/foreign)'},
    {'table': 'per.ocu', 'variable': 'ID_NACIONALIDAD_PAD_N2', 'ES': 'Nacionalidad del progenitor 2 (grandes grupos)',
     'EN': 'Nationality of parent 2 (large groups)'},
    {'table': 'per.ocu', 'variable': 'ID_NACIONALIDAD_PAD_N3', 'ES': 'País de nacionalidad del progenitor 2',
     'EN': 'Country of nationality parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_NHIJOS_NUC', 'ES': 'Número de hijos', 'EN': 'Number of children'},
    {'table': 'per.ocu', 'variable': 'ID_NUC_HOG', 'ES': 'Número núcleos en el hogar',
     'EN': 'Number of family nuclei in the household'},
    {'table': 'per.ocu', 'variable': 'ID_OCU11', 'ES': 'Ocupación a 1 dígito CNO-11',
     'EN': '1-digit occupation CNO-11'},
    {'table': 'per.ocu', 'variable': 'ID_OCU11_CON', 'ES': 'Ocupación del cónyuge a 1 dígito',
     'EN': 'Occupation of the spouse or partner to 1 digit'},
    {'table': 'per.ocu', 'variable': 'ID_OCU11_MAD', 'ES': 'Ocupación del progenitor 1 a 1 dígito',
     'EN': 'Occupation of parent 1 to 1 digit'},
    {'table': 'per.ocu', 'variable': 'ID_OCU11_PAD', 'ES': 'Ocupación del progenitor 2 a 1 dígito',
     'EN': 'Occupation of parent 2 to 1 digit'},
    {'table': 'per.ocu', 'variable': 'ID_PAIS_ANT', 'ES': 'País de residencia anterior',
     'EN': 'Country of previous residence '},
    {'table': 'per.ocu', 'variable': 'ID_PAIS_ANT_GR9', 'ES': 'País de residencia anterior (agregado) ',
     'EN': 'Country of previous residence (aggregated) '},
    {'table': 'per.ocu', 'variable': 'ID_PAIS_DANO', 'ES': 'País de residencia en 2011 ',
     'EN': 'Country of residence in 2011'},
    {'table': 'per.ocu', 'variable': 'ID_PAIS_DANO_GR10', 'ES': 'País residencia en 2011 (agregado)',
     'EN': 'Country of residence in 2011 (aggregated) '},
    {'table': 'per.ocu', 'variable': 'ID_PAIS_PR', 'ES': 'País de procedencia', 'EN': 'Country of origin'},
    {'table': 'per.ocu', 'variable': 'ID_PAIS_PR_GR9', 'ES': 'País de procedencia (grandes grupos)',
     'EN': 'Country of origin (large groups)'},
    {'table': 'per.ocu', 'variable': 'ID_PAIS_UNANO', 'ES': 'País de residencia en 2020 ',
     'EN': 'Country of residence in 2020 '},
    {'table': 'per.ocu', 'variable': 'ID_PAIS_UNANO_GR10', 'ES': 'País de residencia en 2020 (agregado)',
     'EN': 'Country of residence in 2020  (aggregated) '},
    {'table': 'per.ocu', 'variable': 'ID_RELA', 'ES': 'Relación preferente con la actividad (detalle)',
     'EN': 'Current activity status (detail)'},
    {'table': 'per.ocu', 'variable': 'ID_RELA_CON', 'ES': 'Relación con la actividad del cónyuge (detalle)',
     'EN': 'Activity status (detail) of the spouse or partner'},
    {'table': 'per.ocu', 'variable': 'ID_RELA_MAD', 'ES': 'Relación con la actividad del progenitor 1 (detalle)',
     'EN': 'Activity status (detail) parent 1'},
    {'table': 'per.ocu', 'variable': 'ID_RELA_PAD', 'ES': 'Relación con la actividad del progenitor 2 (detalle)',
     'EN': 'Activity status (detail) of parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_RELA2', 'ES': 'Relación preferente con la actividad (activo /inactivo)',
     'EN': 'Current activity status (active/inactive)'},
    {'table': 'per.ocu', 'variable': 'ID_RESI_2011_N1', 'ES': 'CC.AA. de residencia en 2011',
     'EN': 'Autonomous Community of residence in 2011'},
    {'table': 'per.ocu', 'variable': 'ID_RESI_2011_N2', 'ES': 'Provincia de residencia en 2011',
     'EN': 'Province of residence in 2011'},
    {'table': 'per.ocu', 'variable': 'ID_RESI_2011_N3', 'ES': 'Municipio de residencia en 2011',
     'EN': 'Municipality of residence in 2011'},
    {'table': 'per.ocu', 'variable': 'ID_RESI_2020_N1', 'ES': 'CC.AA. de residencia en 2020',
     'EN': 'Autonomous Community of residence in 2020'},
    {'table': 'per.ocu', 'variable': 'ID_RESI_2020_N2', 'ES': 'Provincia de residencia en 2020',
     'EN': 'Province of residence in 2020'},
    {'table': 'per.ocu', 'variable': 'ID_RESI_2020_N3', 'ES': 'Municipio de residencia en 2020',
     'EN': 'Municipality of residence 2020'},
    {'table': 'per.ocu', 'variable': 'ID_RESI_ANT', 'ES': 'Relación entre residencia anterior y residencia actual ',
     'EN': 'Relationship between previous residence and current residence '},
    {'table': 'per.ocu', 'variable': 'ID_RESI_DANO', 'ES': 'Relación entre residencia en 2011 y actual ',
     'EN': 'Relationship between residence in 2011 and current residence '},
    {'table': 'per.ocu', 'variable': 'ID_RESI_NACIM', 'ES': 'Relación entre lugar de nacimiento y residencia',
     'EN': 'Relationship between place of birth and residence'}, {'table': 'per.ocu', 'variable': 'ID_RESI_NACIM_CON',
                                                                  'ES': 'Relación entre el lugar de nacimiento y el de residencia del cónyuge',
                                                                  'EN': 'Relationship between place of birth and residence of spouse or partner'},
    {'table': 'per.ocu', 'variable': 'ID_RESI_NACIM_MAD',
     'ES': 'Relación entre el lugar de nacimiento y el de residencia del progenitor 1',
     'EN': 'Relationship between place of birth and residence parent 1'},
    {'table': 'per.ocu', 'variable': 'ID_RESI_NACIM_PAD',
     'ES': 'Relación entre el lugar de nacimiento y el de residencia del progenitor 2',
     'EN': 'Relationship between place of birth and residence parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_RESI_UNANO', 'ES': 'Relación entre residencia en 2020 y actual',
     'EN': 'Relationship between residence in 2020 and current residence '},
    {'table': 'per.ocu', 'variable': 'ID_RESIDENCIA_N1', 'ES': 'CC.AA. de residencia', 'EN': 'Autonomous Community'},
    {'table': 'per.ocu', 'variable': 'ID_RESIDENCIA_N2', 'ES': 'Provincia de residencia',
     'EN': 'Province of residence'},
    {'table': 'per.ocu', 'variable': 'ID_RESIDENCIA_N3', 'ES': 'Municipio de residencia',
     'EN': 'Municipality of residence'},
    {'table': 'per.ocu', 'variable': 'ID_RESIDENCIA_N4', 'ES': 'Distrito ', 'EN': 'District '},
    {'table': 'per.ocu', 'variable': 'ID_RESIDENCIA_N5', 'ES': 'Sección ', 'EN': 'Section'},
    {'table': 'per.ocu', 'variable': 'ID_SEXO', 'ES': 'Sexo', 'EN': 'Sex'},
    {'table': 'per.ocu', 'variable': 'ID_SEXO_CON', 'ES': 'Sexo del cónyuge', 'EN': 'Sex of spouse or partner '},
    {'table': 'per.ocu', 'variable': 'ID_SEXO_MAD', 'ES': 'Sexo del progenitor 1', 'EN': 'Sex of parent 1'},
    {'table': 'per.ocu', 'variable': 'ID_SEXO_PAD', 'ES': 'Sexo del  progenitor 2', 'EN': 'Sex of parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_SITU', 'ES': 'Situación profesional', 'EN': 'Status in employment'},
    {'table': 'per.ocu', 'variable': 'ID_SITU_CON', 'ES': 'Situación profesional del cónyuge',
     'EN': 'Status in employment of the spouse or partner'},
    {'table': 'per.ocu', 'variable': 'ID_SITU_MAD', 'ES': 'Situación profesional del progenitor 1',
     'EN': 'Status in employment of parent 1'},
    {'table': 'per.ocu', 'variable': 'ID_SITU_PAD', 'ES': 'Situación profesional del progenitor 2',
     'EN': 'Status in employment of parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_SUP_OCU_VIV', 'ES': 'Superficie por ocupante',
     'EN': 'Useful floor space per occupant'},
    {'table': 'per.ocu', 'variable': 'ID_SUP_VIV', 'ES': 'Superficie ', 'EN': 'Useful floor space'},
    {'table': 'per.ocu', 'variable': 'ID_TAM_HOG_6', 'ES': 'Tamaño del hogar', 'EN': 'Size of the household '},
    {'table': 'per.ocu', 'variable': 'ID_TAM_MUN_11', 'ES': 'Tamaño de municipio de residencia',
     'EN': 'Size of municipality of residence'},
    {'table': 'per.ocu', 'variable': 'ID_TAM_MUN_12', 'ES': 'Tamaño de municipio de nacimiento',
     'EN': 'Size of municipality of birth'},
    {'table': 'per.ocu', 'variable': 'ID_TAM_MUN_ANT_12', 'ES': 'Tamaño de municipio de residencia anterior',
     'EN': 'Size of municipality previous residence'},
    {'table': 'per.ocu', 'variable': 'ID_TAM_NUC_1', 'ES': 'Tamaño del núcleo', 'EN': 'Family nucleus size'},
    {'table': 'per.ocu', 'variable': 'ID_TAMANO_MUN_DANO', 'ES': 'Tamaño de municipio de residencia en 2011',
     'EN': 'Size of municipality of residence in 2011'},
    {'table': 'per.ocu', 'variable': 'ID_TAMANO_MUN_EST', 'ES': 'Tamaño del municipio de estudio',
     'EN': 'Size of municipality of study'},
    {'table': 'per.ocu', 'variable': 'ID_TAMANO_MUN_NAC_CON_12', 'ES': 'Tamaño de municipio de nacimiento del cónyuge',
     'EN': 'Size of municipality of birth of spouse or partner'},
    {'table': 'per.ocu', 'variable': 'ID_TAMANO_MUN_NAC_MAD_12',
     'ES': 'Tamaño de municipio de nacimiento del progenitor 1', 'EN': 'Size of municipality of birth parent 1'},
    {'table': 'per.ocu', 'variable': 'ID_TAMANO_MUN_NAC_PAD_12',
     'ES': 'Tamaño de municipio de nacimiento del progenitor 2', 'EN': 'Size of municipality of birth parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_TAMANO_MUN_PR', 'ES': 'Tamaño de municipio de procedencia',
     'EN': 'Size of municipality of origin'},
    {'table': 'per.ocu', 'variable': 'ID_TAMANO_MUN_UNANO', 'ES': 'Tamaño de municipio de residencia en 2020',
     'EN': 'Size of municipality of residence in 2020'},
    {'table': 'per.ocu', 'variable': 'ID_TENEN_VIV', 'ES': 'Régimen de tenencia de la vivienda',
     'EN': 'Tenure status of dwelling '},
    {'table': 'per.ocu', 'variable': 'ID_TESCUR', 'ES': 'Tipo de estudios en curso',
     'EN': 'Field of studies in progress'},
    {'table': 'per.ocu', 'variable': 'ID_TIPO_EDIF_VIV', 'ES': 'Tipo de viviendas según tipo de edificio ',
     'EN': 'Type of dwellings according to type of building '},
    {'table': 'per.ocu', 'variable': 'ID_TIPO_HOG_1', 'ES': 'Tipo de Hogar (detalle)',
     'EN': 'Type of Household (detail)'},
    {'table': 'per.ocu', 'variable': 'ID_TIPO_MUN_DEGURBA', 'ES': 'Tipo de municipio según grado de urbanización',
     'EN': 'Type of municipality according to degree of urbanization'},
    {'table': 'per.ocu', 'variable': 'ID_TIPO_NUC_1', 'ES': 'Tipo de núcleo', 'EN': 'Type of Family Nucleus'},
    {'table': 'per.ocu', 'variable': 'ID_TIPO_PAR_NUC_1', 'ES': 'Tipo de pareja (de hecho o de derecho)',
     'EN': 'Type of couple (de facto or de jure)'},
    {'table': 'per.ocu', 'variable': 'ID_TIPO_PAR_NUC_2', 'ES': 'Tipo de pareja (mismo sexo', 'EN': 'distinto sexo)',
     None: ['Type of couple (same sex', 'different sex)']},
    {'table': 'per.ocu', 'variable': 'ID_ULT_RESI_ANT_N1', 'ES': 'CC.AA. de residencia anterior',
     'EN': 'Previous Autonomous Community of residence'},
    {'table': 'per.ocu', 'variable': 'ID_ULT_RESI_ANT_N2', 'ES': 'Provincia de residencia anterior',
     'EN': 'Previous Province of residence'},
    {'table': 'per.ocu', 'variable': 'ID_ULT_RESI_ANT_N3', 'ES': 'Municipio de residencia anterior',
     'EN': 'Previous Municipality of residence'},
    {'table': 'per.ocu', 'variable': 'ID_VARANOC', 'ES': 'Año de llegada a la CC.AA.',
     'EN': 'Year of arrival to the Autonomous Community'},
    {'table': 'per.ocu', 'variable': 'ID_VARANOE', 'ES': 'Año de llegada a España', 'EN': 'Year of arrival to Spain'},
    {'table': 'per.ocu', 'variable': 'ID_VARANOE_CON', 'ES': 'Año de llegada a España del cónyuge',
     'EN': 'Year of arrival to Spain for spouse or partner'},
    {'table': 'per.ocu', 'variable': 'ID_VARANOE_MAD', 'ES': 'Año de llegada a España del progenitor 1',
     'EN': 'Year of arrival to Spain parent 1'},
    {'table': 'per.ocu', 'variable': 'ID_VARANOE_PAD', 'ES': 'Año de llegada a España del progenitor 2',
     'EN': 'Year of arrival to Spain parent 2'},
    {'table': 'per.ocu', 'variable': 'ID_VARANOM', 'ES': 'Año de llegada al municipio',
     'EN': 'Year of arrival in the municipality'},
    {'table': 'per.ocu', 'variable': 'ID_VARANOP', 'ES': 'Año de llegada a la provincia ',
     'EN': 'Year of arrival to the province '},
    {'table': 'per.ocu', 'variable': 'ID_VARANORES', 'ES': 'Año de llegada a la vivienda',
     'EN': 'Year of arrival to the dwelling'},
    {'table': 'per.ocu', 'variable': 'ID_VAREDAD_CON', 'ES': 'Edad del cónyuge (año a año)',
     'EN': 'Age of spouse or partner (year to year)'},
    {'table': 'per.ocu', 'variable': 'ID_VAREDAD_MAD', 'ES': 'Edad del progenitor 1 (año a año)',
     'EN': 'Age of parent 1 (year to year)'},
    {'table': 'per.ocu', 'variable': 'ID_VAREDAD_PAD', 'ES': 'Edad del progenitor 2 (año a año)',
     'EN': 'Age of parent 2 (year to year)'},
    {'table': 'per.ppal', 'variable': 'ID_CLASE_VIV', 'ES': 'Clase de vivienda', 'EN': 'Class of Dwelling'},
    {'table': 'per.ppal', 'variable': 'ID_EDAD', 'ES': 'Edad año a año', 'EN': 'Age year to year'},
    {'table': 'per.ppal', 'variable': 'ID_ESCUR', 'ES': 'Nivel más alto de la enseñanza principal que cursa',
     'EN': 'Highest level of the primary studies in course'},
    {'table': 'per.ppal', 'variable': 'ID_ESCUR2', 'ES': 'Nivel más alto de otras enseñanzas',
     'EN': 'si cursa más de una', None: ['Highest level of other studies', 'if more than one is being pursued']},
    {'table': 'per.ppal', 'variable': 'ID_ESREAL_CNEDA', 'ES': 'Nivel de estudios (detalle)',
     'EN': 'Educational attainment (detail)'},
    {'table': 'per.ppal', 'variable': 'ID_ESREAL_GR5', 'ES': 'Nivel de estudios (grado)',
     'EN': 'Educational attainment (grade)'},
    {'table': 'per.ppal', 'variable': 'ID_ESTADO_CIVIL', 'ES': 'Estado Civil', 'EN': 'Legal Marital Status'},
    {'table': 'per.ppal', 'variable': 'ID_GRAN_GRUPO_EDAD', 'ES': 'Edad en grandes grupos',
     'EN': 'Age in large groups'},
    {'table': 'per.ppal', 'variable': 'ID_GRUPO_Q_EDAD', 'ES': 'Edad (grupos quinquenales)',
     'EN': 'Age (five-year groups)'},
    {'table': 'per.ppal', 'variable': 'ID_L_EST8', 'ES': 'Lugar de estudio', 'EN': 'Place of study'},
    {'table': 'per.ppal', 'variable': 'ID_LUGAR_EST_N1', 'ES': 'CC.AA. de estudio',
     'EN': 'Autonomous Community of study'},
    {'table': 'per.ppal', 'variable': 'ID_LUGAR_EST_N2', 'ES': 'Provincia de estudio', 'EN': 'Province of study'},
    {'table': 'per.ppal', 'variable': 'ID_LUGAR_EST_N3', 'ES': 'Municipio de estudio', 'EN': 'Municipality of study'},
    {'table': 'per.ppal', 'variable': 'ID_LUGAR_NAC_EXT_N1', 'ES': 'Lugar de nacimiento (España/Extranjero)',
     'EN': 'Place of birth (Spain/abroad)'},
    {'table': 'per.ppal', 'variable': 'ID_LUGAR_NAC_EXT_N2', 'ES': 'País de nacimiento (grandes grupos)',
     'EN': 'Country of birth (large groups)'},
    {'table': 'per.ppal', 'variable': 'ID_LUGAR_NAC_EXT_N3', 'ES': 'País de nacimiento', 'EN': 'Country of birth'},
    {'table': 'per.ppal', 'variable': 'ID_LUGAR_NAC_NAC_N1', 'ES': 'CC.AA. de nacimiento',
     'EN': 'Autonomous Community of birth'},
    {'table': 'per.ppal', 'variable': 'ID_LUGAR_NAC_NAC_N2', 'ES': 'Provincia de nacimiento',
     'EN': 'Province of birth'},
    {'table': 'per.ppal', 'variable': 'ID_LUGAR_NAC_NAC_N3', 'ES': 'Municipio de nacimiento',
     'EN': 'Municipality of birth'}, {'table': 'per.ppal', 'variable': 'ID_LUGAR_PR_N1', 'ES': 'CC.AA. de procedencia',
                                      'EN': 'Autonomous Community of origin'},
    {'table': 'per.ppal', 'variable': 'ID_LUGAR_PR_N2', 'ES': 'Provincia de procedencia', 'EN': 'Province of origin'},
    {'table': 'per.ppal', 'variable': 'ID_LUGAR_PR_N3', 'ES': 'Municipio de procedencia',
     'EN': 'Municipality of origin'},
    {'table': 'per.ppal', 'variable': 'ID_NACIONALIDAD_N1', 'ES': 'Nacionalidad (española/extranjera)',
     'EN': 'Nationality (Spanish/foreign)'},
    {'table': 'per.ppal', 'variable': 'ID_NACIONALIDAD_N2', 'ES': 'Nacionalidad (grandes grupos)',
     'EN': 'Nationality (large groups)'},
    {'table': 'per.ppal', 'variable': 'ID_NACIONALIDAD_N3', 'ES': 'País de nacionalidad',
     'EN': 'Country of nationality'},
    {'table': 'per.ppal', 'variable': 'ID_PAIS_ANT', 'ES': 'País de residencia anterior',
     'EN': 'Country of previous residence '},
    {'table': 'per.ppal', 'variable': 'ID_PAIS_ANT_GR9', 'ES': 'País de residencia anterior (agregado) ',
     'EN': 'Country of previous residence (aggregated) '},
    {'table': 'per.ppal', 'variable': 'ID_PAIS_DANO', 'ES': 'País de residencia en 2011 ',
     'EN': 'Country of residence in 2011'},
    {'table': 'per.ppal', 'variable': 'ID_PAIS_DANO_GR10', 'ES': 'País residencia en 2011 (agregado)',
     'EN': 'Country of residence in 2011 (aggregated) '},
    {'table': 'per.ppal', 'variable': 'ID_PAIS_PR', 'ES': 'País de procedencia', 'EN': 'Country of origin'},
    {'table': 'per.ppal', 'variable': 'ID_PAIS_PR_GR9', 'ES': 'País de procedencia (grandes grupos)',
     'EN': 'Country of origin (large groups)'},
    {'table': 'per.ppal', 'variable': 'ID_PAIS_UNANO', 'ES': 'País de residencia en 2020 ',
     'EN': 'Country of residence in 2020 '},
    {'table': 'per.ppal', 'variable': 'ID_PAIS_UNANO_GR10', 'ES': 'País de residencia en 2020 (agregado)',
     'EN': 'Country of residence in 2020  (aggregated) '},
    {'table': 'per.ppal', 'variable': 'ID_RELA', 'ES': 'Relación preferente con la actividad (detalle)',
     'EN': 'Current activity status (detail)'},
    {'table': 'per.ppal', 'variable': 'ID_RELA2', 'ES': 'Relación preferente con la actividad (activo /inactivo)',
     'EN': 'Current activity status (active/inactive)'},
    {'table': 'per.ppal', 'variable': 'ID_RESI_2011_N1', 'ES': 'CC.AA. de residencia en 2011',
     'EN': 'Autonomous Community of residence in 2011'},
    {'table': 'per.ppal', 'variable': 'ID_RESI_2011_N2', 'ES': 'Provincia de residencia en 2011',
     'EN': 'Province of residence in 2011'},
    {'table': 'per.ppal', 'variable': 'ID_RESI_2011_N3', 'ES': 'Municipio de residencia en 2011',
     'EN': 'Municipality of residence in 2011'},
    {'table': 'per.ppal', 'variable': 'ID_RESI_2020_N1', 'ES': 'CC.AA. de residencia en 2020',
     'EN': 'Autonomous Community of residence in 2020'},
    {'table': 'per.ppal', 'variable': 'ID_RESI_2020_N2', 'ES': 'Provincia de residencia en 2020',
     'EN': 'Province of residence in 2020'},
    {'table': 'per.ppal', 'variable': 'ID_RESI_2020_N3', 'ES': 'Municipio de residencia en 2020',
     'EN': 'Municipality of residence 2020'},
    {'table': 'per.ppal', 'variable': 'ID_RESI_ANT', 'ES': 'Relación entre residencia anterior y residencia actual ',
     'EN': 'Relationship between previous residence and current residence '},
    {'table': 'per.ppal', 'variable': 'ID_RESI_DANO', 'ES': 'Relación entre residencia en 2011 y actual ',
     'EN': 'Relationship between residence in 2011 and current residence '},
    {'table': 'per.ppal', 'variable': 'ID_RESI_NACIM', 'ES': 'Relación entre lugar de nacimiento y residencia',
     'EN': 'Relationship between place of birth and residence'},
    {'table': 'per.ppal', 'variable': 'ID_RESI_UNANO', 'ES': 'Relación entre residencia en 2020 y actual',
     'EN': 'Relationship between residence in 2020 and current residence '},
    {'table': 'per.ppal', 'variable': 'ID_RESIDENCIA_N1', 'ES': 'CC.AA. de residencia', 'EN': 'Autonomous Community'},
    {'table': 'per.ppal', 'variable': 'ID_RESIDENCIA_N2', 'ES': 'Provincia de residencia',
     'EN': 'Province of residence'},
    {'table': 'per.ppal', 'variable': 'ID_RESIDENCIA_N3', 'ES': 'Municipio de residencia',
     'EN': 'Municipality of residence'},
    {'table': 'per.ppal', 'variable': 'ID_RESIDENCIA_N4', 'ES': 'Distrito ', 'EN': 'District '},
    {'table': 'per.ppal', 'variable': 'ID_RESIDENCIA_N5', 'ES': 'Sección ', 'EN': 'Section'},
    {'table': 'per.ppal', 'variable': 'ID_SEXO', 'ES': 'Sexo', 'EN': 'Sex'},
    {'table': 'per.ppal', 'variable': 'ID_TAM_MUN_11', 'ES': 'Tamaño de municipio de residencia',
     'EN': 'Size of municipality of residence'},
    {'table': 'per.ppal', 'variable': 'ID_TAM_MUN_12', 'ES': 'Tamaño de municipio de nacimiento',
     'EN': 'Size of municipality of birth'},
    {'table': 'per.ppal', 'variable': 'ID_TAM_MUN_ANT_12', 'ES': 'Tamaño de municipio de residencia anterior',
     'EN': 'Size of municipality previous residence'},
    {'table': 'per.ppal', 'variable': 'ID_TAMANO_MUN_DANO', 'ES': 'Tamaño de municipio de residencia en 2011',
     'EN': 'Size of municipality of residence in 2011'},
    {'table': 'per.ppal', 'variable': 'ID_TAMANO_MUN_EST', 'ES': 'Tamaño del municipio de estudio',
     'EN': 'Size of municipality of study'},
    {'table': 'per.ppal', 'variable': 'ID_TAMANO_MUN_PR', 'ES': 'Tamaño de municipio de procedencia',
     'EN': 'Size of municipality of origin'},
    {'table': 'per.ppal', 'variable': 'ID_TAMANO_MUN_UNANO', 'ES': 'Tamaño de municipio de residencia en 2020',
     'EN': 'Size of municipality of residence in 2020'},
    {'table': 'per.ppal', 'variable': 'ID_TESCUR', 'ES': 'Tipo de estudios en curso',
     'EN': 'Field of studies in progress'},
    {'table': 'per.ppal', 'variable': 'ID_TIPO_MUN_DEGURBA', 'ES': 'Tipo de municipio según grado de urbanización',
     'EN': 'Type of municipality according to degree of urbanization'},
    {'table': 'per.ppal', 'variable': 'ID_ULT_RESI_ANT_N1', 'ES': 'CC.AA. de residencia anterior',
     'EN': 'Previous Autonomous Community of residence'},
    {'table': 'per.ppal', 'variable': 'ID_ULT_RESI_ANT_N2', 'ES': 'Provincia de residencia anterior',
     'EN': 'Previous Province of residence'},
    {'table': 'per.ppal', 'variable': 'ID_ULT_RESI_ANT_N3', 'ES': 'Municipio de residencia anterior',
     'EN': 'Previous Municipality of residence'},
    {'table': 'per.ppal', 'variable': 'ID_VARANOC', 'ES': 'Año de llegada a la CC.AA.',
     'EN': 'Year of arrival to the Autonomous Community'},
    {'table': 'per.ppal', 'variable': 'ID_VARANOE', 'ES': 'Año de llegada a España', 'EN': 'Year of arrival to Spain'},
    {'table': 'per.ppal', 'variable': 'ID_VARANOM', 'ES': 'Año de llegada al municipio',
     'EN': 'Year of arrival in the municipality'},
    {'table': 'per.ppal', 'variable': 'ID_VARANOP', 'ES': 'Año de llegada a la provincia ',
     'EN': 'Year of arrival to the province '},
    {'table': 'per.ppal', 'variable': 'ID_VARANORES', 'ES': 'Año de llegada a la vivienda',
     'EN': 'Year of arrival to the dwelling'},
    {'table': 'viv.fam', 'variable': 'ID_ANO_CONS', 'ES': 'Año de construcción (todo)',
     'EN': 'Year of construction (detail)'},
    {'table': 'viv.fam', 'variable': 'ID_ANO_CONS_GR11', 'ES': 'Año de construcción (agregado)',
     'EN': 'Year of construction  (aggregated)'},
    {'table': 'viv.fam', 'variable': 'ID_CLASE_VIV_FAM', 'ES': 'Clase de vivienda familiar',
     'EN': 'Class of main family dwelling'},
    {'table': 'viv.fam', 'variable': 'ID_NPLANTAS_BAJO_EDIF', 'ES': 'Número plantas bajo rasante',
     'EN': 'Number of floors below ground level'},
    {'table': 'viv.fam', 'variable': 'ID_NPLANTAS_SOBRE_EDIF', 'ES': 'Número plantas sobre rasante',
     'EN': 'Number of floors above ground level'},
    {'table': 'viv.fam', 'variable': 'ID_RESIDENCIA_N1', 'ES': 'CC.AA. de residencia', 'EN': 'Autonomous Community'},
    {'table': 'viv.fam', 'variable': 'ID_RESIDENCIA_N2', 'ES': 'Provincia de residencia',
     'EN': 'Province of residence'},
    {'table': 'viv.fam', 'variable': 'ID_RESIDENCIA_N3', 'ES': 'Municipio de residencia',
     'EN': 'Municipality of residence'},
    {'table': 'viv.fam', 'variable': 'ID_RESIDENCIA_N4', 'ES': 'Distrito ', 'EN': 'District '},
    {'table': 'viv.fam', 'variable': 'ID_RESIDENCIA_N5', 'ES': 'Sección ', 'EN': 'Section'},
    {'table': 'viv.fam', 'variable': 'ID_SUP_OCU_VIV', 'ES': 'Superficie por ocupante',
     'EN': 'Useful floor space per occupant'},
    {'table': 'viv.fam', 'variable': 'ID_SUP_VIV', 'ES': 'Superficie ', 'EN': 'Useful floor space'},
    {'table': 'viv.fam', 'variable': 'ID_TAM_HOG_6', 'ES': 'Tamaño del hogar', 'EN': 'Size of the household '},
    {'table': 'viv.fam', 'variable': 'ID_TAM_MUN_VIV', 'ES': 'Tamaño de municipio de residencia',
     'EN': 'Size of municipality of residence'},
    {'table': 'viv.fam', 'variable': 'ID_TENEN_VIV', 'ES': 'Régimen de tenencia de la vivienda',
     'EN': 'Tenure status of dwelling '},
    {'table': 'viv.fam', 'variable': 'ID_TIPO_EDIF_VIV', 'ES': 'Tipo de viviendas según tipo de edificio ',
     'EN': 'Type of dwellings according to type of building '},
    {'table': 'viv.fam', 'variable': 'ID_TIPO_MUN_DEGURBA', 'ES': 'Tipo de municipio según grado de urbanización',
     'EN': 'Type of municipality according to degree of urbanization'},
    {'table': 'viv.fam', 'variable': 'ID_TIPO_VIV_USO', 'ES': 'Tipo de vivienda según uso',
     'EN': 'Class of family dwelling according to use'},
    {'table': 'viv.ppal', 'variable': 'ID_ACT22', 'ES': 'Actividad establecimiento a 1 letra CNAE-09',
     'EN': 'Economic activity at 1 letter CNAE-09'},
    {'table': 'viv.ppal', 'variable': 'ID_ACT273', 'ES': 'Actividad establecimiento a 3 dígitos CNAE-09',
     'EN': 'Economic activity3-digit CNAE-09'},
    {'table': 'viv.ppal', 'variable': 'ID_ACT5', 'ES': 'Actividad establecimiento (rama)',
     'EN': 'Economic activity  (branch)'},
    {'table': 'viv.ppal', 'variable': 'ID_ACT89', 'ES': 'Actividad establecimiento a 2 dígitos CNAE-09',
     'EN': 'Economic activity 2-digit CNAE-09'},
    {'table': 'viv.ppal', 'variable': 'ID_CLASE_VIV', 'ES': 'Clase de vivienda', 'EN': 'Class of Dwelling'},
    {'table': 'viv.ppal', 'variable': 'ID_EDAD', 'ES': 'Edad año a año', 'EN': 'Age year to year'},
    {'table': 'viv.ppal', 'variable': 'ID_ESCUR', 'ES': 'Nivel más alto de la enseñanza principal que cursa',
     'EN': 'Highest level of the primary studies in course'},
    {'table': 'viv.ppal', 'variable': 'ID_ESCUR2', 'ES': 'Nivel más alto de otras enseñanzas',
     'EN': 'si cursa más de una', None: ['Highest level of other studies', 'if more than one is being pursued']},
    {'table': 'viv.ppal', 'variable': 'ID_ESREAL_CNEDA', 'ES': 'Nivel de estudios (detalle)',
     'EN': 'Educational attainment (detail)'},
    {'table': 'viv.ppal', 'variable': 'ID_ESREAL_GR5', 'ES': 'Nivel de estudios (grado)',
     'EN': 'Educational attainment (grade)'},
    {'table': 'viv.ppal', 'variable': 'ID_ESTADO_CIVIL', 'ES': 'Estado Civil', 'EN': 'Legal Marital Status'},
    {'table': 'viv.ppal', 'variable': 'ID_GRAN_GRUPO_EDAD', 'ES': 'Edad en grandes grupos',
     'EN': 'Age in large groups'},
    {'table': 'viv.ppal', 'variable': 'ID_GRUPO_Q_EDAD', 'ES': 'Edad (grupos quinquenales)',
     'EN': 'Age (five-year groups)'},
    {'table': 'viv.ppal', 'variable': 'ID_L_EST8', 'ES': 'Lugar de estudio', 'EN': 'Place of study'},
    {'table': 'viv.ppal', 'variable': 'ID_L_TRAB7', 'ES': 'Lugar de trabajo', 'EN': 'Place of work'},
    {'table': 'viv.ppal', 'variable': 'ID_LUGAR_EST_N1', 'ES': 'CC.AA. de estudio',
     'EN': 'Autonomous Community of study'},
    {'table': 'viv.ppal', 'variable': 'ID_LUGAR_EST_N2', 'ES': 'Provincia de estudio', 'EN': 'Province of study'},
    {'table': 'viv.ppal', 'variable': 'ID_LUGAR_EST_N3', 'ES': 'Municipio de estudio', 'EN': 'Municipality of study'},
    {'table': 'viv.ppal', 'variable': 'ID_LUGAR_NAC_EXT_N1', 'ES': 'Lugar de nacimiento (España/Extranjero)',
     'EN': 'Place of birth (Spain/abroad)'},
    {'table': 'viv.ppal', 'variable': 'ID_LUGAR_NAC_EXT_N2', 'ES': 'País de nacimiento (grandes grupos)',
     'EN': 'Country of birth (large groups)'},
    {'table': 'viv.ppal', 'variable': 'ID_LUGAR_NAC_EXT_N3', 'ES': 'País de nacimiento', 'EN': 'Country of birth'},
    {'table': 'viv.ppal', 'variable': 'ID_LUGAR_NAC_NAC_N1', 'ES': 'CC.AA. de nacimiento',
     'EN': 'Autonomous Community of birth'},
    {'table': 'viv.ppal', 'variable': 'ID_LUGAR_NAC_NAC_N2', 'ES': 'Provincia de nacimiento',
     'EN': 'Province of birth'},
    {'table': 'viv.ppal', 'variable': 'ID_LUGAR_NAC_NAC_N3', 'ES': 'Municipio de nacimiento',
     'EN': 'Municipality of birth'}, {'table': 'viv.ppal', 'variable': 'ID_LUGAR_TRAB_N1', 'ES': 'CC.AA. de trabajo',
                                      'EN': 'Autonomous Community of work'},
    {'table': 'viv.ppal', 'variable': 'ID_LUGAR_TRAB_N2', 'ES': 'Provincia de trabajo', 'EN': 'Province of work'},
    {'table': 'viv.ppal', 'variable': 'ID_LUGAR_TRAB_N3', 'ES': 'Municipio de trabajo', 'EN': 'Municipality of work'},
    {'table': 'viv.ppal', 'variable': 'ID_NACIONALIDAD_N1', 'ES': 'Nacionalidad (española/extranjera)',
     'EN': 'Nationality (Spanish/foreign)'},
    {'table': 'viv.ppal', 'variable': 'ID_NACIONALIDAD_N2', 'ES': 'Nacionalidad (grandes grupos)',
     'EN': 'Nationality (large groups)'},
    {'table': 'viv.ppal', 'variable': 'ID_NACIONALIDAD_N3', 'ES': 'País de nacionalidad',
     'EN': 'Country of nationality'}, {'table': 'viv.ppal', 'variable': 'ID_OCU11', 'ES': 'Ocupación a 1 dígito CNO-11',
                                       'EN': '1-digit occupation CNO-11'},
    {'table': 'viv.ppal', 'variable': 'ID_OCU171', 'ES': 'Ocupación a 3 dígitos CNO-11',
     'EN': '3-digit occupation CNO-11'},
    {'table': 'viv.ppal', 'variable': 'ID_OCU63', 'ES': 'Ocupación a 2 dígitos CNO-11',
     'EN': '2-digit occupation CNO-11'},
    {'table': 'viv.ppal', 'variable': 'ID_PAIS_PR_GR9', 'ES': 'País de procedencia (grandes grupos)',
     'EN': 'Country of origin (large groups)'},
    {'table': 'viv.ppal', 'variable': 'ID_RESI_NACIM', 'ES': 'Relación entre lugar de nacimiento y residencia',
     'EN': 'Relationship between place of birth and residence'},
    {'table': 'viv.ppal', 'variable': 'ID_RESIDENCIA_N1', 'ES': 'CC.AA. de residencia', 'EN': 'Autonomous Community'},
    {'table': 'viv.ppal', 'variable': 'ID_RESIDENCIA_N2', 'ES': 'Provincia de residencia',
     'EN': 'Province of residence'},
    {'table': 'viv.ppal', 'variable': 'ID_RESIDENCIA_N3', 'ES': 'Municipio de residencia',
     'EN': 'Municipality of residence'},
    {'table': 'viv.ppal', 'variable': 'ID_RESIDENCIA_N4', 'ES': 'Distrito ', 'EN': 'District '},
    {'table': 'viv.ppal', 'variable': 'ID_RESIDENCIA_N5', 'ES': 'Sección ', 'EN': 'Section'},
    {'table': 'viv.ppal', 'variable': 'ID_SEXO', 'ES': 'Sexo', 'EN': 'Sex'},
    {'table': 'viv.ppal', 'variable': 'ID_SITU', 'ES': 'Situación profesional', 'EN': 'Status in employment'},
    {'table': 'viv.ppal', 'variable': 'ID_TAM_MUN_11', 'ES': 'Tamaño de municipio de residencia',
     'EN': 'Size of municipality of residence'},
    {'table': 'viv.ppal', 'variable': 'ID_TAM_MUN_12', 'ES': 'Tamaño de municipio de nacimiento',
     'EN': 'Size of municipality of birth'},
    {'table': 'viv.ppal', 'variable': 'ID_TAMANO_MUN_EST', 'ES': 'Tamaño del municipio de estudio',
     'EN': 'Size of municipality of study'},
    {'table': 'viv.ppal', 'variable': 'ID_TAMANO_MUN_TRAB', 'ES': 'Tamaño del municipio de trabajo',
     'EN': 'Size of municipality of work'},
    {'table': 'viv.ppal', 'variable': 'ID_TESCUR', 'ES': 'Tipo de estudios en curso',
     'EN': 'Field of studies in progress'},
    {'table': 'viv.ppal', 'variable': 'ID_TIPO_MUN_DEGURBA', 'ES': 'Tipo de municipio según grado de urbanización',
     'EN': 'Type of municipality according to degree of urbanization'},
    {'table': 'viv.ppal', 'variable': 'ID_VARANOE', 'ES': 'Año de llegada a España', 'EN': 'Year of arrival to Spain'}]
